name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  # renovate: datasource=npm depName=pnpm
  PNPM_VERSION: 7.33.7

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: pnpm/action-setup@v4.1.0
        with:
          version: ${{ env.PNPM_VERSION }}

      - uses: actions/setup-node@v4.2.0
        with:
          node-version: 14.x
          cache: pnpm

      - run: pnpm install
      - run: pnpm lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: pnpm/action-setup@v4.1.0
        with:
          version: ${{ env.PNPM_VERSION }}

      - uses: actions/setup-node@v4.2.0
        with:
          node-version: 14.x
          cache: pnpm

      - run: pnpm install
      - run: pnpm test
