name: Release

on:
  push:
    tags:
      - '*'

env:
  # renovate: datasource=npm depName=pnpm
  PNPM_VERSION: 9.15.5

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - uses: pnpm/action-setup@v4.0.0
        with:
          version: ${{ env.PNPM_VERSION }}

      - uses: actions/setup-node@v4.2.0
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: 14.x
          cache: pnpm

      - run: pnpm install
      - run: pnpm build

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}